import { Document } from "@langchain/core/documents"
import { BaseMessage } from "@langchain/core/messages"
import { Annotation, MessagesAnnotation } from "@langchain/langgraph"
import type { EnrichedDocument } from "../types/pubmed.js"

export const InputStateAnnotation = Annotation.Root({
    messages: Annotation<BaseMessage[]>
})

export const StateAnnotation = Annotation.Root({
    ...MessagesAnnotation.spec,

    retrievedDocs: Annotation<Document[]>,

    // Scope classification result (set by scopeClassifier, used for routing)
    isMedical: Annotation<boolean | undefined>({
        reducer: (x, y) => y ?? x,
        default: () => undefined
    }),

    // Optimized query for vector search (generated by queryParser)
    optimizedQuery: Annotation<string | undefined>({
        reducer: (x, y) => y ?? x,
        default: () => undefined
    }),

    // Enriched documents with PubMed metadata (generated by pubmedEnricher)
    enrichedDocs: Annotation<EnrichedDocument[]>({
        reducer: (x, y) => y ?? x,
        default: () => []
    })
})
